name: open-games-rlib
version: '0.1.0.0'
synopsis: Rlib interface to open games engine
category: Math
author: George Karachalias, Noon van der Silk, Philipp Zahn
maintainer: philipp.m.zahn@gmail.com
copyright: Philipp Zahn
license: MIT
extra-source-files:
- README.md


library:
  source-dirs: src
  exposed-modules:
    - Examples.ExternalEnvironment.PD
    - Examples.ExternalEnvironment.RockPaperScissors
    - Examples.ExternalEnvironment.TrustGame
    - Examples.ExternalEnvironment.MontyHall

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - comonad
  - containers
  - criterion
  - extra
  - fgl
  - generic-random
  - graphviz
  - lens
  - mtl
  - mwc-random
  - NumInstances
  - open-games-hs
  - optparse-applicative
  - parsec
  - poly
  - probability
  - profunctors
  - random
  - servant
  - servant-server
  - servant-websockets
  - splitmix
  - template-haskell
  - transformers
  - typed-process
  - wai
  - warp
  - websockets

executables:
  # Servers for RL-training
  serve-game:
    main:        Main.hs
    source-dirs: serve-game
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - open-games-rlib

